#!/bin/bash
#
# Description:
# Set the preferred package building config in the autogit.config file e.g. var=3
#
DIR=$HOME/autogit
# Load Config
configdir=$DIR
. $configdir/autogit.config
#. autogit.config
#
# Update, install, build packages from Github repos with available PKGBUILD
function githubversion {
while IFS="" read -r p || [ -n "$p" ]
do
  echo ""
  cd "$DIR"
  printf '%s\n' "$p"
  curl --silent "https://raw.githubusercontent.com/"$p"/master/PKGBUILD" | grep 'pkgver=' | cut -c 8-
  if [ -e "$DIR/packages/$p" ] # If file exists
  then
    echo "file does exist local"
    cd "$DIR/packages/$p"
    ls
    url=$(curl --silent "https://raw.githubusercontent.com/"$p"/master/PKGBUILD" | grep 'pkgver=' | cut -c 8-)
    localfile=$(cat $(pwd)/PKGBUILD | grep 'pkgver=' | cut -c 8-)
    if [ "$url" == "$localfile" ]
    then
    echo -e "\e[7mUp to date!\e[0m"
    else
    echo -e "\e[7mOut of date! Updating ...\e[0m"
    git fetch origin
    git checkout master
    git reset --hard origin/master # reset files to how they were before
    git clean -f -d # clear any other changes you've done
    if [ "$var" == "1" ] 
    then
    ls
    cd ..
    folder="$(ls)"
    buildpkg -c -p $folder
    mv /var/cache/manjaro-tools/pkg/stable/x86_64/*.*.tar.* "$DIR/binary"
    else
    if [ "$var" == "0" ]
    then
    time makepkg -src
    mv *.*.tar.xz "$DIR/binary"
    else
    if [ "$var" == "2" ]
    then
    time makepkg -srci
    mv *.*.tar.xz "$DIR/binary"
    else
    if [ "$var" == "3" ]
    then
    ls
    cd ..
    folder="$(ls)"
    buildpkg -b unstable -c -p $folder
    mv /var/cache/manjaro-tools/pkg/unstable/x86_64/*.*.tar.* "$DIR/binary"
    fi
    fi
    fi
    fi
    fi
  else
    echo "file does not exist local, downloading ..."
    mkdir -p "$DIR/packages/$p" && cd "$DIR/packages/$p"
    git clone https://github.com/"$p".git
    folder="$(ls)"
    echo "$folder"
    mv $folder original
    cd original
    ls
    mv * .* "$DIR/packages/$p"
    cd "$DIR/packages/$p"
    rm -rf original
    mkdir -p "$DIR/binary"
    if [ "$var" == "1" ] 
    then
    updpkgsums
    cd .. && buildpkg -c -p $folder
    mv /var/cache/manjaro-tools/pkg/stable/x86_64/*.*.tar.* "$DIR/binary"
    else
    if [ "$var" == "0" ]
    then
    updpkgsums
    time makepkg -src
    mv *.*.tar.xz "$DIR/binary"
    else
    if [ "$var" == "2" ]
    then
    updpkgsums
    time makepkg -srci
    mv *.*.tar.xz "$DIR/binary"
    else
    if [ "$var" == "3" ]
    then
    updpkgsums
    cd .. && buildpkg -b unstable -c -p $folder
    mv /var/cache/manjaro-tools/pkg/unstable/x86_64/*.*.tar.* "$DIR/binary"
    fi
    fi
    fi
    fi
    fi
done < $HOME/autogit/reponames/github
}
#
clear
githubversion
